version: '3'

services:
  app:
    build: .
    ports:
    - "8888:8888"
    networks:
    - main
    environment:
      DB_HOST: db
      HONEYCOMB_WRITEKEY: 

  db:
    image: mysql
    networks:
    - main
    volumes:
    - shoutr-golang:/var/lib
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # value is arbitrary
      MYSQL_DATABASE: "shoutr"          # create DB shoutr automatically

volumes:
  shoutr-golang:

networks:
  main:
    driver: bridge
