version: '3'

services:
  app:
    build: .
    ports:
    - "8888:8888"
    networks:
    - main
    environment:
      DB_HOST: db
      HONEYCOMB_WRITEKEY: 

  db:
    image: mysql
    networks:
    - main
    volumes:
    - example-golang-webapp:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # value is arbitrary
      MYSQL_DATABASE: "shoutr"          # create DB shoutr automatically
      ENV: "dev"

volumes:
  example-golang-webapp:

networks:
  main:
    driver: bridge
