version: '3'

services:
  honeytail-docker:
    build: .
    command: --debug --parser=keyval --dataset=docker.ce-logs --writekey=$HONEYCOMB_WRITEKEY --keyval.timefield=time --file=/var/log/docker.log
    volumes:
    - /var/log/docker-ce.err.log:/var/log/docker.log
    - honeytail-tmp:/tmp
    environment:
      HONEYCOMB_WRITEKEY: 

volumes:
  honeytail-tmp:
    driver: local
