version: '3'

services:
  app:
    build: .
    ports:
    - "5000:5000"
    networks:
    - main
    environment:
      DB_HOST: db
      HONEYCOMB_WRITEKEY: 

  db:
    image: mysql
    networks:
    - main
    volumes:
    - example-python-api:/var/lib
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "example-python-api"

volumes:
  example-python-api:

networks:
  main:
    driver: bridge
