source 'https://rubygems.org'

# Sinatra driver
gem 'sinatra', '~> 1.0'
gem 'sinatra-contrib'

gem 'activerecord', '~>5.1.2'
gem 'activesupport', '~>5.1.2'

gem 'rake'

gem 'honeycomb-beeline'
gem 'shotgun', '~>0.9.1'

gem 'httparty'

group :test do
  gem 'rack-test'
  gem 'rspec', '~>3.0'
  gem 'shoulda-matchers'
end

group :test, :development do
  gem 'factory_girl'
  gem 'pry-byebug'
end
