service: node-serverless-app

custom:
  bucket: node-serverless-store

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:PutObjectTagging
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource: "arn:aws:s3:::${self:custom.bucket}"
  environment:
    bucket: "${self:custom.bucket}"

functions:
  persist:
    handler: handler.persist
    events:
      - http:
          path: /
          method: post

resources:
  Resources:
    InstrumentationTutorialStoreS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "${self:custom.bucket}"
        LifecycleConfiguration:
          Rules:
            - Id: DeleteEverythingInAMonth
              Status: Enabled
              ExpirationInDays: 30
